os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build -vv
  - cargo build -vv --example gcj-2016-qualifier-a
  - cargo test -vv
  - cargo doc -vv
matrix:
  allow_failures:
    - rust:
      - nightly
