os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo build --example gcj-2016-qualifier-a --verbose
  - cargo test --verbose
  - cargo doc --verbose
matrix:
  allow_failures:
    - rust:
      - nightly
