matrix:
  allow_failures:
    - CHANNEL: nightly
environment:
  matrix:
    - ARCH: i586
      ABI: msvc
      CHANNEL: stable
      EXTRA_ARGS:
    - ARCH: i586
      ABI: msvc
      CHANNEL: beta
      EXTRA_ARGS:
    - ARCH: i586
      ABI: msvc
      CHANNEL: nightly
      EXTRA_ARGS: --features clippy
    - ARCH: i686
      ABI: gnu
      CHANNEL: stable
      EXTRA_ARGS:
    - ARCH: i686
      ABI: gnu
      CHANNEL: beta
      EXTRA_ARGS:
    - ARCH: i686
      ABI: gnu
      CHANNEL: nightly
      EXTRA_ARGS: --features clippy
    - ARCH: i686
      ABI: msvc
      CHANNEL: stable
      EXTRA_ARGS:
    - ARCH: i686
      ABI: msvc
      CHANNEL: beta
      EXTRA_ARGS:
    - ARCH: i686
      ABI: msvc
      CHANNEL: nightly
      EXTRA_ARGS: --features clippy
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: stable
      EXTRA_ARGS:
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: beta
      EXTRA_ARGS:
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: nightly
      EXTRA_ARGS: --features clippy
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: stable
      EXTRA_ARGS:
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: beta
      EXTRA_ARGS:
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: nightly
      EXTRA_ARGS: --features clippy
install:
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin
  - SET TARGET=%ARCH%-pc-windows-%ABI%
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - IF "%ARCH%"=="i586" (
      rustup-init.exe -y --no-modify-path --default-host i686-pc-windows-msvc --default-toolchain %CHANNEL% &&
      rustup target add %TARGET%
    ) ELSE (
      rustup-init.exe -y --no-modify-path --default-host %TARGET% --default-toolchain %CHANNEL%
    )
  - rustup --version
  - rustc --version
  - rustdoc --version
  - cargo --version
build_script:
  - cargo build --verbose --target=%TARGET% %EXTRA_ARGS% &&
    cargo build --example gcj-2016-qualifier-a --verbose --target=%TARGET% %EXTRA_ARGS% &&
    cargo doc --verbose --target=%TARGET% %EXTRA_ARGS%
test_script:
  - cargo test --verbose --target=%TARGET% %EXTRA_ARGS%
