matrix:
  allow_failures:
    - CHANNEL: nightly
environment:
  matrix:
    - ARCH: i586
      ABI: msvc
      CHANNEL: stable
      EXTRA_FEATURES:
    - ARCH: i586
      ABI: msvc
      CHANNEL: beta
      EXTRA_FEATURES:
    - ARCH: i586
      ABI: msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - ARCH: i686
      ABI: gnu
      CHANNEL: stable
      EXTRA_FEATURES:
    - ARCH: i686
      ABI: gnu
      CHANNEL: beta
      EXTRA_FEATURES:
    - ARCH: i686
      ABI: gnu
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - ARCH: i686
      ABI: msvc
      CHANNEL: stable
      EXTRA_FEATURES:
    - ARCH: i686
      ABI: msvc
      CHANNEL: beta
      EXTRA_FEATURES:
    - ARCH: i686
      ABI: msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: stable
      EXTRA_FEATURES:
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: beta
      EXTRA_FEATURES:
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: stable
      EXTRA_FEATURES:
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: beta
      EXTRA_FEATURES:
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
install:
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin
  - SET TARGET=%ARCH%-pc-windows-%ABI%
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - IF "%ARCH%"=="i586" (
      rustup-init.exe -y --no-modify-path --default-host i686-pc-windows-%ABI% --default-toolchain %CHANNEL% &&
      rustup target add %TARGET%
    ) ELSE (
      rustup-init.exe -y --no-modify-path --default-host %TARGET% --default-toolchain %CHANNEL%
    )
  - rustup --version
  - rustc --version
  - rustdoc --version
  - cargo --version
build_script:
  - cargo build -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
  - cargo build -vv --target=%TARGET% --features "parallel %EXTRA_FEATURES%"
  - cargo build -vv --target=%TARGET% --example gcj-2016-qualifier-a --features "%EXTRA_FEATURES%"
  - cargo build -vv --target=%TARGET% --example gcj-2016-qualifier-a --features "parallel %EXTRA_FEATURES%"
  - cargo doc -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
  - cargo doc -vv --target=%TARGET% --features "parallel %EXTRA_FEATURES%"
test_script:
  - cargo test -vv --target=%TARGET% --features "parallel %EXTRA_FEATURES%"
