matrix:
  allow_failures:
    - CHANNEL: nightly
environment:
  matrix:
    - TARGET: i586-pc-windows-msvc
      CHANNEL: stable
    - TARGET: i586-pc-windows-msvc
      CHANNEL: beta
    - TARGET: i586-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
    - TARGET: i686-pc-windows-gnu
      CHANNEL: beta
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
    - TARGET: i686-pc-windows-msvc
      CHANNEL: beta
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
install:
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - IF "%TARGET%"=="i586-pc-windows-msvc" (
      rustup-init.exe -y --no-modify-path --default-host i686-pc-windows-msvc --default-toolchain %CHANNEL% &&
      rustup target add %TARGET%
    ) ELSE (
      rustup-init.exe -y --no-modify-path --default-host %TARGET% --default-toolchain %CHANNEL%
    )
  - rustup --version
  - rustc --version
  - rustdoc --version
  - cargo --version
build_script:
  - IF "%CHANNEL%" == "nightly" (
      cargo build --verbose --target=%TARGET% --features clippy &&
      cargo build --example gcj-2016-qualifier-a --verbose --target=%TARGET% --features clippy &&
      cargo doc --verbose --target=%TARGET% --features clippy
    ) ELSE (
      cargo build --verbose --target=%TARGET% &&
      cargo build --example gcj-2016-qualifier-a --verbose --target=%TARGET% &&
      cargo doc --verbose --target=%TARGET%
    )
test_script:
  - IF "%CHANNEL%" == "nightly" (
      cargo test --verbose --target=%TARGET% --features clippy
    ) ELSE (
      cargo test --target=%TARGET% --verbose
    )
